//! The engine: one task that owns a workspace's connection and its slice of
//! the store, and is the only thing allowed to talk to either.
//!
//! The interface is deliberately narrow. The UI sends a `Command` and receives
//! an `Event`; it never awaits, never queries SQLite, and never holds a lock
//! that the network could block. That is what keeps a slow request from
//! freezing the screen, which is the failure every terminal chat client is
//! judged on.

use anyhow::Result;
use slk_api::{HistoryQuery, RtEvent, SlackBackend};
use slk_core::{ChannelId, Delivery, Message, TeamId, Ts, UserId};
use slk_store::{CountUpdate, Store, StoredConversation};
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::mpsc;
use tracing::{debug, warn};

/// What the interface asks the engine to do.
#[derive(Debug, Clone)]
pub enum Command {
    /// Show this conversation: cached messages immediately, fresh ones after.
    Open(ChannelId),
    /// Scrollback reached the top.
    LoadOlder(ChannelId, Ts),
    OpenThread(ChannelId, Ts),
    Send {
        channel: ChannelId,
        thread: Option<Ts>,
        text: String,
        /// Generated by the caller so the optimistic row can be matched to its
        /// confirmation without guessing.
        local_id: String,
        /// Slack's "also send to channel" for a thread reply.
        broadcast: bool,
    },
    /// Follow or stop following a thread.
    FollowThread {
        channel: ChannelId,
        thread: Ts,
        on: bool,
    },
    MarkRead(ChannelId, Ts),
    /// Toggle one reaction. Applied optimistically, rolled back on failure.
    React {
        channel: ChannelId,
        ts: Ts,
        name: String,
        on: bool,
    },
    Edit {
        channel: ChannelId,
        ts: Ts,
        text: String,
    },
    Delete(ChannelId, Ts),
    /// Fetch a shareable link; the answer comes back as `Event::Permalink`.
    Permalink(ChannelId, Ts),
    /// Search. `local` uses the offline index instead of asking Slack, which
    /// is instant, works with no network, and covers every workspace at once —
    /// but only what has been read.
    Search {
        query: String,
        local: bool,
    },
    /// Open a conversation positioned on one message, from a search result.
    JumpToMessage(ChannelId, Ts),
    /// Fetch every file on a message to the download directory.
    DownloadFiles {
        channel: ChannelId,
        ts: Ts,
        dir: std::path::PathBuf,
    },
    /// Fetch one image so it can be drawn. Separate from `DownloadFiles`
    /// because this goes to a cache the user never sees, not to their
    /// downloads.
    FetchImage {
        url: String,
        file_id: String,
        dir: std::path::PathBuf,
    },
    UploadFile {
        channel: ChannelId,
        thread: Option<Ts>,
        path: std::path::PathBuf,
        comment: Option<String>,
    },
    /// The lists: threads with replies, messages naming you, and who is in a
    /// conversation.
    /// A slash command, already split into its name and the rest.
    Slash {
        channel: ChannelId,
        command: String,
        text: String,
    },
    /// Save for later, or unsave.
    Save {
        channel: ChannelId,
        ts: Ts,
        on: bool,
    },
    Pin {
        channel: ChannelId,
        ts: Ts,
        on: bool,
    },
    ListSaved,
    /// What is pinned in this conversation.
    ListPinned(ChannelId),
    ListThreads,
    ListMentions,
    /// Tell the conversation we are typing. Throttled by the caller.
    Typing(ChannelId),
    /// Set our own presence: `true` active, `false` away.
    Presence(bool),
    /// Star this conversation, or unstar it.
    Star {
        channel: ChannelId,
        on: bool,
    },
    /// Mute this conversation, or unmute it.
    Mute {
        channel: ChannelId,
        on: bool,
    },
    Leave(ChannelId),
    SetTopic {
        channel: ChannelId,
        topic: String,
    },
    SetPurpose {
        channel: ChannelId,
        purpose: String,
    },
    /// Invite somebody here. `who` is whatever the user typed — a display
    /// name, a handle or an id — and the engine resolves it, because the
    /// engine is the side that holds the directory.
    Invite {
        channel: ChannelId,
        who: String,
    },
    /// Public channels the user is not in.
    BrowseChannels,
    /// Join a public channel and open it.
    Join(ChannelId),
    /// Remember where the user was, for the next start.
    Remember(String),
    ListMembers(ChannelId),
    ShowProfile(UserId),
    Refresh,
    Shutdown,
}

/// What the engine tells the interface.
#[derive(Debug, Clone)]
pub enum Event {
    /// Boot finished; the sidebar is real rather than cached.
    Ready {
        team: TeamId,
        self_id: UserId,
    },
    Conversations(Vec<StoredConversation>),
    Users(Vec<slk_store::UserLabel>),
    /// Id to handle, for rendering and completing `@design-team`.
    UserGroups(Vec<(String, String)>),
    /// A conversation's messages, oldest first. `append` distinguishes a page
    /// of scrollback from a fresh load.
    Messages {
        channel: ChannelId,
        messages: Vec<Message>,
        append_older: bool,
    },
    Thread {
        channel: ChannelId,
        parent: Ts,
        messages: Vec<Message>,
    },
    /// One message arrived or changed. Covers the optimistic row being
    /// confirmed, so the UI replaces rather than duplicates.
    Upserted {
        channel: ChannelId,
        message: Box<Message>,
        replaces: Option<Ts>,
    },
    Deleted {
        channel: ChannelId,
        ts: Ts,
    },
    Typing {
        channel: ChannelId,
        user: UserId,
    },
    Presence {
        users: Vec<UserId>,
        presence: slk_core::Presence,
    },
    Connected,
    Disconnected(String),
    SearchResults {
        query: String,
        local: bool,
        hits: Vec<slk_api::backend::SearchHit>,
    },
    /// A conversation loaded around one particular message.
    MessagesAround {
        channel: ChannelId,
        messages: Vec<Message>,
        focus: Ts,
    },
    /// An image is on disk and can be drawn.
    ImageFetched {
        file_id: String,
        path: std::path::PathBuf,
    },
    /// One of the lists, ready to show.
    List {
        title: String,
        items: Vec<ListRow>,
    },
    Profile(Box<slk_store::StoredUser>),
    /// Show this conversation. Sent when the engine, not the user, decided
    /// which one — after joining one, for instance.
    OpenChannel(ChannelId),
    /// Where this workspace was left last time, if anywhere.
    Restore(ChannelId),
    /// A link, ready to put on the clipboard.
    Permalink {
        channel: ChannelId,
        ts: Ts,
        url: String,
    },
    /// Something happened that the user would want to know about, if they are
    /// not already looking at it. The engine decides whether it *matters*; the
    /// interface decides whether the user can already see it.
    Notify {
        channel: ChannelId,
        conversation: String,
        who: String,
        text: String,
        mention: bool,
    },
    /// Something the user should see, in their words rather than Slack's.
    Notice(String),
    /// Slack asked us to wait. The interface shows it rather than looking
    /// frozen, and it clears itself when the seconds run out.
    RateLimited {
        seconds: u64,
    },
    /// A slash command the workspace would not run. Carries what was typed,
    /// because by the time this arrives the composer has been emptied.
    SlashRejected {
        command: String,
        text: String,
    },
    /// The session is gone; nothing will work until it is replaced.
    AuthLost,
}

/// Whether any keyword appears in the text as a whole word.
///
/// Whole words, because "ops" inside "developer" is not a mention of the ops
/// team, and a keyword that fires on every message is one the user turns off
/// along with every other notification. Keywords are expected lower-cased.
pub fn keyword_matches(keywords: &[String], text: &str) -> bool {
    if keywords.is_empty() {
        return false;
    }
    let lower = text.to_lowercase();
    keywords.iter().any(|k| {
        !k.is_empty()
            && lower.match_indices(k.as_str()).any(|(i, _)| {
                let before = lower[..i].chars().next_back();
                let after = lower[i + k.len()..].chars().next();
                let edge = |c: Option<char>| c.is_none_or(|c| !c.is_alphanumeric() && c != '_');
                edge(before) && edge(after)
            })
    })
}

pub struct Engine {
    backend: Arc<dyn SlackBackend>,
    store: Store,
    events: mpsc::Sender<Event>,
    team: TeamId,
    self_id: UserId,
    /// The conversation the interface is showing, so a reconnect knows which
    /// history to catch up on.
    focused: Option<ChannelId>,
    /// Highlight words, lower-cased once here rather than per message.
    keywords: Vec<String>,
    /// How many messages a page of history holds. Configurable because it
    /// is the one number that trades first paint against how far back a
    /// conversation reads before it has to ask again.
    page: u16,
}

impl Engine {
    /// Start the engine. Returns the command sink and the event source; the
    /// task owns everything else.
    pub fn spawn(
        backend: Arc<dyn SlackBackend>,
        store: Store,
        keywords: Vec<String>,
        page: u16,
    ) -> (mpsc::Sender<Command>, mpsc::Receiver<Event>) {
        let (cmd_tx, cmd_rx) = mpsc::channel(64);
        let (ev_tx, ev_rx) = mpsc::channel(256);
        let team = backend.team().clone();
        let self_id = backend.self_id().clone();

        tokio::spawn(async move {
            let mut engine = Engine {
                backend,
                store,
                events: ev_tx,
                team,
                self_id,
                focused: None,
                keywords: keywords
                    .iter()
                    .map(|k| k.trim().to_lowercase())
                    .filter(|k| !k.is_empty())
                    .collect(),
                page: page.clamp(10, 1000),
            };
            if let Err(e) = engine.run(cmd_rx).await {
                warn!("engine stopped: {e:#}");
            }
        });

        (cmd_tx, ev_rx)
    }

    async fn emit(&mut self, ev: Event) {
        // A closed channel means the UI is gone; that is a shutdown, not an
        // error worth logging on every subsequent send.
        let _ = self.events.send(ev).await;
    }

    async fn run(&mut self, mut cmds: mpsc::Receiver<Command>) -> Result<()> {
        // The sidebar comes from the cache first, so the first frame is
        // instant and correct-as-of-last-time rather than empty.
        self.push_sidebar().await;
        self.emit(Event::Ready {
            team: self.team.clone(),
            self_id: self.self_id.clone(),
        })
        .await;

        self.boot().await;

        // Ask for presence on the people whose dots are actually drawn: the
        // other side of every direct message.
        let watch: Vec<UserId> = self
            .store
            .conversations(&self.team)
            .unwrap_or_default()
            .iter()
            .filter_map(|c| c.peer.clone())
            .collect();

        let mut rt = match self.backend.connect(&watch).await {
            Ok(stream) => {
                self.emit(Event::Connected).await;
                stream
            }
            Err(e) => {
                warn!("realtime unavailable: {e}");
                self.emit(Event::Disconnected(e.user_message())).await;
                None
            }
        };
        // How long to wait before the next attempt. A websocket that drops is
        // the normal state of a long-lived one — a laptop lid, a change of
        // network — so this is a routine path, not an error path.
        let mut backoff = Duration::from_secs(1);
        let mut retry_at: Option<Instant> = None;

        loop {
            tokio::select! {
                cmd = cmds.recv() => {
                    let Some(cmd) = cmd else { return Ok(()) };
                    if matches!(cmd, Command::Shutdown) {
                        return Ok(());
                    }
                    self.handle(cmd).await;
                }
                ev = async {
                    match rt.as_mut() {
                        Some(r) => r.recv().await,
                        // No stream: park forever rather than spinning on None.
                        None => std::future::pending().await,
                    }
                } => {
                    match ev {
                        Some(RtEvent::Disconnected(why)) => {
                            self.emit(Event::Disconnected(why)).await;
                            rt = None;
                            retry_at = Some(Instant::now() + backoff);
                        }
                        // The sender was dropped, which means the socket task
                        // ended without saying why.
                        None => {
                            self.emit(Event::Disconnected("stream ended".into())).await;
                            rt = None;
                            retry_at = Some(Instant::now() + backoff);
                        }
                        Some(e) => self.on_realtime(e).await,
                    }
                }
                // Reconnect, with a jittered wait that grows to a minute.
                // Anything shorter hammers a server that is already unhappy.
                _ = async {
                    match retry_at {
                        Some(at) => tokio::time::sleep_until(at.into()).await,
                        None => std::future::pending().await,
                    }
                }, if rt.is_none() => {
                    retry_at = None;
                    let watch: Vec<UserId> = self
                        .store
                        .conversations(&self.team)
                        .unwrap_or_default()
                        .iter()
                        .filter_map(|c| c.peer.clone())
                        .collect();
                    match self.backend.connect(&watch).await {
                        Ok(stream) => {
                            rt = stream;
                            backoff = Duration::from_secs(1);
                            self.emit(Event::Connected).await;
                            // Whatever arrived while the socket was down did
                            // not arrive as an event, so it has to be fetched.
                            self.fill_gaps().await;
                        }
                        Err(e) => {
                            debug!("reconnect failed: {e}");
                            backoff = (backoff * 2).min(Duration::from_secs(60));
                            retry_at = Some(Instant::now() + backoff);
                        }
                    }
                }
            }
        }
    }

    /// Run a slash command.
    ///
    /// The ones this client understands are done here; everything else goes to
    /// the workspace the way the web client sends it, so an app's `/giphy`
    /// still works. A command that is refused says so rather than vanishing.
    async fn slash(&mut self, channel: ChannelId, command: String, text: String) {
        let result = match command.as_str() {
            "/me" => self.backend.me_message(&channel, &text).await.map(|_| None),
            "/shrug" => {
                let body = format!("{text} ¯\\_(ツ)_/¯");
                self.backend
                    .post(&channel, None, body.trim(), "", false)
                    .await
                    .map(|_| None)
            }
            "/away" | "/active" => {
                Box::pin(self.handle(Command::Presence(command == "/active"))).await;
                return;
            }
            "/status" => {
                let now = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_secs() as i64)
                    .unwrap_or(0);
                let (emoji, rest, expires) = parse_status(&text, now);
                self.backend
                    .set_status(&rest, &emoji, expires)
                    .await
                    .map(|_| {
                        Some(if rest.is_empty() && emoji.is_empty() {
                            "status cleared"
                        } else if expires > 0 {
                            "status set, with an expiry"
                        } else {
                            "status set"
                        })
                    })
            }
            "/dnd" => {
                let minutes = parse_minutes(&text);
                self.backend.snooze(minutes).await.map(|_| {
                    if minutes == 0 {
                        Some("dnd off")
                    } else {
                        Some("snoozing")
                    }
                })
            }
            // These five go back through the command handlers rather than
            // straight at the backend, so that typing `/mute` and pressing the
            // mute key do the same thing to the sidebar. Two implementations
            // of "mute" is how one of them ends up not refreshing.
            "/leave" | "/part" => {
                Box::pin(self.handle(Command::Leave(channel.clone()))).await;
                return;
            }
            "/topic" => {
                Box::pin(self.handle(Command::SetTopic {
                    channel: channel.clone(),
                    topic: text.clone(),
                }))
                .await;
                return;
            }
            "/purpose" => {
                Box::pin(self.handle(Command::SetPurpose {
                    channel: channel.clone(),
                    purpose: text.clone(),
                }))
                .await;
                return;
            }
            "/invite" => {
                Box::pin(self.handle(Command::Invite {
                    channel: channel.clone(),
                    who: text.clone(),
                }))
                .await;
                return;
            }
            "/mute" | "/unmute" => {
                Box::pin(self.handle(Command::Mute {
                    channel: channel.clone(),
                    on: command == "/mute",
                }))
                .await;
                return;
            }
            "/star" | "/unstar" => {
                Box::pin(self.handle(Command::Star {
                    channel: channel.clone(),
                    on: command == "/star",
                }))
                .await;
                return;
            }
            "/join" | "/open" => {
                // `/join #design` and `/join design` both name a channel we
                // may already be in, in which case joining is just opening.
                let want = text.trim().trim_start_matches('#').to_string();
                match self
                    .store
                    .conversations(&self.team)
                    .unwrap_or_default()
                    .into_iter()
                    .find(|c| c.name.eq_ignore_ascii_case(&want))
                {
                    Some(c) if c.is_member => {
                        self.emit(Event::OpenChannel(c.id.clone())).await;
                        self.open(c.id).await;
                    }
                    Some(c) => Box::pin(self.handle(Command::Join(c.id))).await,
                    None => {
                        self.emit(Event::Notice(format!("no channel called {want}")))
                            .await;
                        self.emit(Event::SlashRejected { command, text }).await;
                    }
                }
                return;
            }
            // Anything else belongs to the workspace.
            _ => self
                .backend
                .slash(&channel, &command, &text)
                .await
                .map(|_| None),
        };

        let rejected = result.is_err();
        match result {
            Ok(Some(note)) => self.emit(Event::Notice(note.into())).await,
            Ok(None) => self.open(channel).await,
            // "that no longer exists" is the right words for a deleted
            // message and the wrong ones for a command nobody has installed.
            Err(e) if e.kind == slk_api::ErrorKind::NotFound => {
                self.emit(Event::Notice(format!(
                    "{command} is not a command this workspace knows"
                )))
                .await
            }
            Err(e) => {
                self.emit(Event::Notice(format!("{command}: {}", e.user_message())))
                    .await
            }
        }
        // A command the workspace refused is text the person typed and has
        // now lost. The interface puts it back.
        if rejected {
            self.emit(Event::SlashRejected { command, text }).await;
        }
    }

    /// Fetch what was missed while the socket was down.
    ///
    /// Counts first, because that is one request for every badge. Then the
    /// history of the conversation being read, from the newest message already
    /// held — the rest is left to be loaded when it is opened, which is what
    /// keeps the traffic shaped like one person reading rather than a catch-up
    /// sweep of the whole workspace.
    async fn fill_gaps(&mut self) {
        if self.backend.capabilities().counts {
            if let Ok(counts) = self.backend.counts().await {
                let updates: Vec<CountUpdate> = counts
                    .conversations
                    .into_iter()
                    .map(|c| CountUpdate {
                        id: c.id,
                        last_read: c.last_read,
                        latest: c.latest,
                        unread: c.unread,
                        mentions: c.mentions,
                    })
                    .collect();
                let _ = self.store.apply_counts(&self.team, &updates);
                self.push_sidebar().await;
            }
        }

        let Some(channel) = self.focused.clone() else {
            return;
        };
        let newest = self
            .store
            .latest_messages(&self.team, &channel, &self.self_id, 1)
            .ok()
            .and_then(|m| m.first().map(|m| m.ts.clone()));

        let q = HistoryQuery {
            oldest: newest,
            limit: 200,
            ..Default::default()
        };
        match self.backend.history(&channel, q).await {
            Ok(page) if !page.messages.is_empty() => {
                self.store_page(&page.messages);
                self.emit(Event::Messages {
                    channel,
                    messages: page.messages,
                    append_older: false,
                })
                .await;
            }
            Ok(_) => {}
            Err(e) => debug!("gap fill: {e}"),
        }
    }

    async fn boot(&mut self) {
        match self.backend.boot().await {
            Ok(boot) => {
                let mut convs = boot.conversations;
                // A muted conversation must never raise a badge, and the flag
                // does not live on the channel object.
                for c in convs.iter_mut() {
                    if boot.muted.contains(&c.id) {
                        c.is_muted = true;
                    }
                }
                if let Err(e) = self.store.upsert_conversations(&convs) {
                    warn!("storing conversations: {e:#}");
                    self.emit(Event::Notice(format!("cannot write the cache: {e}")))
                        .await;
                }
                if !boot.users.is_empty() {
                    let _ = self.store.upsert_users(&boot.users);
                }
            }
            Err(e) if e.kind == slk_api::ErrorKind::Auth => {
                self.emit(Event::AuthLost).await;
                return;
            }
            Err(e) => {
                warn!("boot failed: {e}");
                self.emit(Event::Notice(e.user_message())).await;
            }
        }

        // Counts before history: one call gives every badge, where verifying
        // conversations one at a time would be both slow and scraper-shaped.
        if self.backend.capabilities().counts {
            match self.backend.counts().await {
                Ok(counts) => {
                    let updates: Vec<CountUpdate> = counts
                        .conversations
                        .into_iter()
                        .map(|c| CountUpdate {
                            id: c.id,
                            last_read: c.last_read,
                            latest: c.latest,
                            unread: c.unread,
                            mentions: c.mentions,
                        })
                        .collect();
                    if let Err(e) = self.store.apply_counts(&self.team, &updates) {
                        warn!("applying counts: {e:#}");
                    }
                }
                Err(e) => debug!("counts unavailable: {e}"),
            }
        }

        match self.backend.users().await {
            Ok(users) if !users.is_empty() => {
                let _ = self.store.upsert_users(&users);
            }
            Ok(_) => {}
            Err(e) => debug!("users unavailable: {e}"),
        }

        self.resolve_unknown_users().await;
        self.push_sidebar().await;
        self.push_users().await;
        self.push_usergroups().await;

        // Where this workspace was left, offered once and only once. Emitted
        // after the sidebar, so the interface has the conversation to open by
        // the time it is asked to.
        if let Ok(Some(id)) = self.store.kv(&format!("last_open:{}", self.team.as_str())) {
            if !id.is_empty() {
                self.emit(Event::Restore(ChannelId::new(id))).await;
            }
        }
    }

    /// Fetch the users a name is needed for but the directory does not have.
    ///
    /// `users.list` omits Slack's own system accounts and, in a real
    /// workspace, is paged; the first live run showed a direct message titled
    /// `USLACK` because of exactly that.
    async fn resolve_unknown_users(&mut self) {
        let Ok(known) = self.store.user_labels(&self.team) else {
            return;
        };
        let known: std::collections::HashSet<UserId> = known.into_iter().map(|u| u.id).collect();

        let Ok(convs) = self.store.conversations(&self.team) else {
            return;
        };
        let missing: Vec<UserId> = convs
            .iter()
            .filter_map(|c| c.peer.clone())
            .filter(|p| !p.is_empty() && !known.contains(p))
            .collect();

        // A handful at most, and only for conversations already on screen.
        // Resolving every author in history would be scraper-shaped traffic.
        let mut fetched = Vec::new();
        for id in missing.into_iter().take(20) {
            match self.backend.user_info(&id).await {
                Ok(u) => fetched.push(u),
                Err(e) => debug!("cannot resolve {id}: {e}"),
            }
        }
        if !fetched.is_empty() {
            let _ = self.store.upsert_users(&fetched);
        }
    }

    /// Do something to a conversation, mirror it locally, and say so.
    ///
    /// The local write happens only after Slack agrees. A star that appears
    /// and then quietly goes away at the next boot is the shape of bug that
    /// makes people stop trusting the sidebar, so the optimistic path that
    /// suits a reaction is wrong here: these are rare, deliberate acts where
    /// a moment's wait costs nothing.
    async fn conversation_op<F>(&mut self, op: slk_api::backend::ChannelOp, locally: F, note: &str)
    where
        F: FnOnce(&slk_store::Store, &TeamId) -> anyhow::Result<()>,
    {
        match self.backend.channel_op(op).await {
            Ok(()) => {
                if let Err(e) = locally(&self.store, &self.team) {
                    warn!("mirroring a conversation change: {e:#}");
                }
                self.push_sidebar().await;
                self.emit(Event::Notice(note.into())).await;
            }
            Err(e) => self.emit(Event::Notice(e.user_message())).await,
        }
    }

    /// Turn what somebody typed into a user id.
    ///
    /// `@alice`, `alice`, `Alice Brennan` and `U0ALICE` all reach the same
    /// person; anything else reaches nobody, which is better than inviting
    /// the wrong one.
    fn resolve_user(&self, who: &str) -> Option<UserId> {
        let want = who.trim().trim_start_matches('@');
        if want.is_empty() {
            return None;
        }
        let labels = self.store.user_labels(&self.team).ok()?;
        if let Some(u) = labels.iter().find(|u| u.id.as_str() == want) {
            return Some(u.id.clone());
        }
        labels
            .iter()
            .find(|u| u.label.eq_ignore_ascii_case(want))
            .or_else(|| {
                labels
                    .iter()
                    .find(|u| u.label.to_lowercase().starts_with(&want.to_lowercase()))
            })
            .map(|u| u.id.clone())
    }

    async fn push_sidebar(&mut self) {
        match self.store.conversations(&self.team) {
            Ok(convs) => self.emit(Event::Conversations(convs)).await,
            Err(e) => {
                // An empty sidebar with the reason only in a log file is the
                // hardest kind of bug to report. Say it on screen.
                warn!("reading conversations: {e:#}");
                self.emit(Event::Notice(format!("cannot read the cache: {e}")))
                    .await;
            }
        }
    }

    async fn push_usergroups(&mut self) {
        // A failure here costs a completion, not a client: the mention still
        // renders, because Slack sends the handle inline with it.
        if let Ok(groups) = self.backend.usergroups().await {
            if !groups.is_empty() {
                self.emit(Event::UserGroups(groups)).await;
            }
        }
    }

    async fn push_users(&mut self) {
        if let Ok(users) = self.store.user_labels(&self.team) {
            self.emit(Event::Users(users)).await;
        }
    }

    /// Run one command, and say so if it left us rate limited.
    ///
    /// Asked here rather than at each of the twenty places a request can fail,
    /// because being rate limited is a state the client is in rather than one
    /// command's bad luck — and because the backend is the only thing that
    /// knows how long it has to last.
    async fn handle(&mut self, cmd: Command) {
        self.dispatch(cmd).await;
        if let Some(left) = self.backend.paused_for().await {
            self.emit(Event::RateLimited {
                seconds: left.as_secs().max(1),
            })
            .await;
        }
    }

    async fn dispatch(&mut self, cmd: Command) {
        match cmd {
            Command::Open(ch) => self.open(ch).await,
            Command::LoadOlder(ch, before) => self.load_older(ch, before).await,
            Command::OpenThread(ch, parent) => self.open_thread(ch, parent).await,
            Command::Send {
                channel,
                thread,
                text,
                local_id,
                broadcast,
            } => self.send(channel, thread, text, local_id, broadcast).await,
            Command::FollowThread {
                channel,
                thread,
                on,
            } => match self.backend.follow_thread(&channel, &thread, on).await {
                Ok(()) => {
                    self.emit(Event::Notice(
                        if on {
                            "following this thread"
                        } else {
                            "no longer following"
                        }
                        .to_string(),
                    ))
                    .await
                }
                Err(e) => {
                    self.emit(Event::Notice(format!("not changed: {}", e.user_message())))
                        .await
                }
            },
            Command::MarkRead(ch, ts) => self.mark_read(ch, ts).await,
            Command::React {
                channel,
                ts,
                name,
                on,
            } => {
                if let Err(e) = self.backend.react(&channel, &ts, &name, on).await {
                    // The optimistic chip is already on screen, so the failure
                    // has to say so or the user believes the reaction landed.
                    self.emit(Event::Notice(format!(
                        "reaction not saved: {}",
                        e.user_message()
                    )))
                    .await;
                    self.refresh_message(&channel, &ts).await;
                }
            }
            Command::Edit { channel, ts, text } => {
                match self.backend.edit(&channel, &ts, &text).await {
                    Ok(()) => self.refresh_message(&channel, &ts).await,
                    Err(e) => {
                        self.emit(Event::Notice(format!("not edited: {}", e.user_message())))
                            .await
                    }
                }
            }
            Command::Delete(channel, ts) => match self.backend.delete(&channel, &ts).await {
                Ok(()) => self.emit(Event::Deleted { channel, ts }).await,
                Err(e) => {
                    self.emit(Event::Notice(format!("not deleted: {}", e.user_message())))
                        .await
                }
            },
            Command::Permalink(channel, ts) => match self.backend.permalink(&channel, &ts).await {
                Ok(url) => self.emit(Event::Permalink { channel, ts, url }).await,
                Err(e) => {
                    self.emit(Event::Notice(format!("no link: {}", e.user_message())))
                        .await
                }
            },
            Command::Search { query, local } => {
                let hits = if local {
                    self.store
                        .search(&query, 50)
                        .unwrap_or_default()
                        .into_iter()
                        .map(|(_, channel, ts, text)| {
                            let channel_name = self
                                .store
                                .conversations(&self.team)
                                .unwrap_or_default()
                                .into_iter()
                                .find(|c| c.id == channel)
                                .map(|c| c.name)
                                .unwrap_or_default();
                            slk_api::backend::SearchHit {
                                channel,
                                channel_name,
                                ts,
                                user: None,
                                text,
                            }
                        })
                        .collect()
                } else {
                    match self.backend.search(&query, 50).await {
                        Ok(h) => h,
                        Err(e) => {
                            self.emit(Event::Notice(e.user_message())).await;
                            Vec::new()
                        }
                    }
                };
                self.emit(Event::SearchResults { query, local, hits }).await;
            }

            Command::JumpToMessage(channel, ts) => {
                // Load a window around the message, not just after it, so the
                // result arrives with the context that makes it readable.
                let before = self
                    .backend
                    .history(
                        &channel,
                        HistoryQuery {
                            latest: Some(ts.clone()),
                            limit: 25,
                            inclusive: true,
                            ..Default::default()
                        },
                    )
                    .await
                    .map(|p| p.messages)
                    .unwrap_or_default();
                let after = self
                    .backend
                    .history(
                        &channel,
                        HistoryQuery {
                            oldest: Some(ts.clone()),
                            limit: 25,
                            ..Default::default()
                        },
                    )
                    .await
                    .map(|p| p.messages)
                    .unwrap_or_default();

                let mut messages = before;
                messages.extend(after);
                messages.sort_by(|a, b| a.ts.cmp(&b.ts));
                messages.dedup_by(|a, b| a.ts == b.ts);
                self.store_page(&messages);
                self.emit(Event::MessagesAround {
                    channel,
                    messages,
                    focus: ts,
                })
                .await;
            }

            Command::DownloadFiles { channel, ts, dir } => {
                let Some(m) = self
                    .store
                    .thread(&self.team, &channel, &self.self_id, &ts)
                    .unwrap_or_default()
                    .into_iter()
                    .find(|m| m.ts == ts)
                else {
                    self.emit(Event::Notice("that message is no longer here".into()))
                        .await;
                    return;
                };
                if m.files.is_empty() {
                    self.emit(Event::Notice("no files on this message".into()))
                        .await;
                    return;
                }
                for f in &m.files {
                    // A file with no URL is one Slack will not hand over —
                    // usually a deleted upload or one from a workspace the
                    // session cannot reach. Saying so beats saving nothing and
                    // reporting nothing.
                    let Some(url) = &f.url_private else {
                        self.emit(Event::Notice(format!(
                            "{}: Slack gave no address for this file",
                            f.name
                        )))
                        .await;
                        continue;
                    };
                    // Never write outside the download directory, whatever the
                    // server called the file.
                    let name = std::path::Path::new(&f.name)
                        .file_name()
                        .map(|n| n.to_string_lossy().to_string())
                        .unwrap_or_else(|| "file".into());
                    let to = unique_path(&dir.join(name));
                    match self.backend.download(url, &to).await {
                        Ok(n) => {
                            self.emit(Event::Notice(format!(
                                "saved {} ({})",
                                to.display(),
                                human_size(n)
                            )))
                            .await
                        }
                        Err(e) => {
                            self.emit(Event::Notice(format!("{}: {}", f.name, e.user_message())))
                                .await
                        }
                    }
                }
            }

            Command::FetchImage { url, file_id, dir } => {
                let to = dir.join(&file_id);
                if to.exists() {
                    self.emit(Event::ImageFetched { file_id, path: to }).await;
                    return;
                }
                match self.backend.download(&url, &to).await {
                    Ok(_) => self.emit(Event::ImageFetched { file_id, path: to }).await,
                    // Silent: a picture that will not come is a placeholder,
                    // not something to interrupt the user about.
                    Err(e) => debug!("image {file_id}: {e}"),
                }
            }

            Command::UploadFile {
                channel,
                thread,
                path,
                comment,
            } => {
                if !path.is_file() {
                    self.emit(Event::Notice(format!("no such file: {}", path.display())))
                        .await;
                    return;
                }
                match self
                    .backend
                    .upload(&channel, thread.as_ref(), &path, comment.as_deref())
                    .await
                {
                    Ok(()) => {
                        self.emit(Event::Notice(format!(
                            "sent {}",
                            path.file_name().unwrap_or_default().to_string_lossy()
                        )))
                        .await;
                        // The websocket echo brings the message itself; on the
                        // mock there is none, so refresh either way.
                        self.open(channel).await;
                    }
                    Err(e) => {
                        self.emit(Event::Notice(format!("not sent: {}", e.user_message())))
                            .await
                    }
                }
            }

            Command::Slash {
                channel,
                command,
                text,
            } => self.slash(channel, command, text).await,

            Command::Save { channel, ts, on } => match self.backend.save(&channel, &ts, on).await {
                Ok(()) => {
                    self.emit(Event::Notice(
                        if on { "saved for later" } else { "unsaved" }.into(),
                    ))
                    .await;
                    self.refresh_message(&channel, &ts).await;
                }
                Err(e) => self.emit(Event::Notice(e.user_message())).await,
            },

            Command::Pin { channel, ts, on } => match self.backend.pin(&channel, &ts, on).await {
                Ok(()) => {
                    self.emit(Event::Notice(if on { "pinned" } else { "unpinned" }.into()))
                        .await;
                    self.refresh_message(&channel, &ts).await;
                }
                Err(e) => self.emit(Event::Notice(e.user_message())).await,
            },

            Command::ListSaved => {
                let names = self.store.user_labels(&self.team).unwrap_or_default();
                let _ = names;
                let rows = self
                    .store
                    .saved(&self.team, 100)
                    .unwrap_or_default()
                    .into_iter()
                    .map(|(channel, ts, text)| ListRow {
                        label: one_line(&text),
                        note: String::new(),
                        target: ListTarget::Message(channel, ts),
                    })
                    .collect();
                self.emit(Event::List {
                    title: "saved".into(),
                    items: rows,
                })
                .await;
            }

            Command::ListPinned(ch) => {
                // Ask Slack first: the store knows about a pin only for the
                // history it has read, and the pin worth showing is often on
                // a message from months ago.
                let mut note = String::new();
                if let Ok(all) = self.backend.pins(&ch).await {
                    match self.store.set_pinned(&self.team, &ch, &all) {
                        Ok(0) => {}
                        Ok(n) => {
                            note = format!("{n} older than what is cached");
                        }
                        Err(e) => warn!("reconciling pins: {e:#}"),
                    }
                }
                let mut rows: Vec<ListRow> = self
                    .store
                    .pinned(&self.team, &ch, 100)
                    .unwrap_or_default()
                    .into_iter()
                    .map(|(ts, text)| ListRow {
                        label: one_line(&text),
                        note: String::new(),
                        target: ListTarget::Message(ch.clone(), ts),
                    })
                    .collect();
                // Said rather than omitted: a pinned list that quietly drops
                // what it cannot reach is worse than a short one that admits
                // it, because the user cannot tell the two apart.
                if !note.is_empty() {
                    rows.push(ListRow {
                        label: note,
                        note: String::new(),
                        target: ListTarget::Info,
                    });
                }
                self.emit(Event::List {
                    title: "pinned".into(),
                    items: rows,
                })
                .await;
            }

            Command::Presence(active) => match self.backend.set_presence(active).await {
                Ok(()) => {
                    self.emit(Event::Notice(if active { "active" } else { "away" }.into()))
                        .await
                }
                Err(e) => self.emit(Event::Notice(e.user_message())).await,
            },

            Command::Typing(ch) => {
                // Never worth a notice and never worth a retry: an indicator
                // that arrives late is worse than one that does not arrive.
                let _ = self.backend.typing(&ch).await;
            }

            Command::Star { channel, on } => {
                self.conversation_op(
                    slk_api::backend::ChannelOp::Star(channel.clone(), on),
                    |st, team| st.set_starred(team, &channel, on),
                    if on { "starred" } else { "unstarred" },
                )
                .await;
            }

            Command::Mute { channel, on } => {
                // The endpoint writes the whole muted set, so the local flag
                // moves first and the list is read back from the store. If
                // the write fails the flag is put back, which is why this one
                // does not go through `conversation_op`.
                let before = self.store.muted(&self.team).unwrap_or_default();
                if let Err(e) = self.store.set_muted(&self.team, &channel, on) {
                    self.emit(Event::Notice(format!("cannot write the cache: {e}")))
                        .await;
                    return;
                }
                let after = self.store.muted(&self.team).unwrap_or_default();
                match self
                    .backend
                    .channel_op(slk_api::backend::ChannelOp::SetMuted(after))
                    .await
                {
                    Ok(()) => {
                        self.push_sidebar().await;
                        self.emit(Event::Notice(if on { "muted" } else { "unmuted" }.into()))
                            .await;
                    }
                    Err(e) => {
                        let _ =
                            self.store
                                .set_muted(&self.team, &channel, before.contains(&channel));
                        self.push_sidebar().await;
                        self.emit(Event::Notice(e.user_message())).await;
                    }
                }
            }

            Command::Leave(channel) => {
                self.conversation_op(
                    slk_api::backend::ChannelOp::Leave(channel.clone()),
                    |st, team| st.set_membership(team, &channel, false),
                    "left",
                )
                .await;
            }

            Command::SetTopic { channel, topic } => {
                self.conversation_op(
                    slk_api::backend::ChannelOp::SetTopic(channel.clone(), topic.clone()),
                    |st, team| st.set_topic(team, &channel, &topic),
                    "topic set",
                )
                .await;
            }

            Command::SetPurpose { channel, purpose } => {
                self.conversation_op(
                    slk_api::backend::ChannelOp::SetPurpose(channel.clone(), purpose.clone()),
                    |st, team| st.set_purpose(team, &channel, &purpose),
                    "purpose set",
                )
                .await;
            }

            Command::Invite { channel, who } => match self.resolve_user(&who) {
                Some(id) => {
                    self.conversation_op(
                        slk_api::backend::ChannelOp::Invite(channel, id),
                        |_, _| Ok(()),
                        "invited",
                    )
                    .await
                }
                None => {
                    self.emit(Event::Notice(format!("nobody here is called {who}")))
                        .await
                }
            },

            Command::Remember(where_) => {
                // Best effort by design: failing to remember where someone was
                // is not worth a message, and the next start simply opens the
                // first conversation as it always did.
                let _ = self
                    .store
                    .set_kv(&format!("last_open:{}", self.team.as_str()), &where_);
            }

            Command::Join(ch) => {
                use slk_api::backend::ChannelOp;
                match self.backend.channel_op(ChannelOp::Join(ch.clone())).await {
                    Ok(()) => {
                        // Re-boot rather than inventing the conversation
                        // locally: Slack knows its topic, its member count and
                        // whether it is really joined, and a row assembled
                        // here would differ from the one that arrives next.
                        if let Ok(boot) = self.backend.boot().await {
                            let _ = self.store.upsert_conversations(&boot.conversations);
                        }
                        self.push_sidebar().await;
                        self.emit(Event::Notice("joined".into())).await;
                        self.emit(Event::OpenChannel(ch.clone())).await;
                        self.open(ch).await;
                    }
                    Err(e) => {
                        self.emit(Event::Notice(format!("cannot join: {}", e.user_message())))
                            .await
                    }
                }
            }

            Command::BrowseChannels => {
                match self.backend.public_channels(200).await {
                    Ok(chans) => {
                        // Only the ones you are not in: the sidebar already
                        // has the rest, and a picker that lists both makes you
                        // read it twice.
                        let mut rows: Vec<ListRow> = chans
                            .into_iter()
                            .filter(|c| !c.is_member)
                            .map(|c| ListRow {
                                label: format!("#{}", c.name),
                                note: match c.member_count {
                                    Some(n) => format!("{n} members"),
                                    None => String::new(),
                                },
                                target: ListTarget::Join(c.id),
                            })
                            .collect();
                        rows.sort_by(|a, b| a.label.cmp(&b.label));
                        self.emit(Event::List {
                            title: "join a channel".into(),
                            items: rows,
                        })
                        .await;
                    }
                    Err(e) => {
                        self.emit(Event::Notice(format!(
                            "cannot list channels: {}",
                            e.user_message()
                        )))
                        .await
                    }
                }
            }

            Command::ListThreads => {
                let rows = self
                    .store
                    .threads(&self.team, 100)
                    .unwrap_or_default()
                    .into_iter()
                    .map(|(channel, ts, text, replies)| ListRow {
                        label: one_line(&text),
                        note: format!("{replies} repl{}", if replies == 1 { "y" } else { "ies" }),
                        target: ListTarget::Thread(channel, ts),
                    })
                    .collect();
                self.emit(Event::List {
                    title: "threads".into(),
                    items: rows,
                })
                .await;
            }

            Command::ListMentions => {
                let names = self.store.user_labels(&self.team).unwrap_or_default();
                let rows = self
                    .store
                    .mentions(&self.team, &self.self_id, 100)
                    .unwrap_or_default()
                    .into_iter()
                    .map(|(channel, ts, text, author)| ListRow {
                        label: one_line(&text),
                        note: names
                            .iter()
                            .find(|u| u.id.as_str() == author)
                            .map(|u| u.label.clone())
                            .unwrap_or(author),
                        target: ListTarget::Message(channel, ts),
                    })
                    .collect();
                self.emit(Event::List {
                    title: "mentions".into(),
                    items: rows,
                })
                .await;
            }

            Command::ListMembers(ch) => {
                let ids = match self.backend.members(&ch).await {
                    Ok(v) => v,
                    Err(e) => {
                        self.emit(Event::Notice(e.user_message())).await;
                        return;
                    }
                };
                // Fill in anyone the directory does not know, so the list is
                // names rather than ids.
                let known: std::collections::HashSet<UserId> = self
                    .store
                    .user_labels(&self.team)
                    .unwrap_or_default()
                    .into_iter()
                    .map(|u| u.id)
                    .collect();
                let mut fetched = Vec::new();
                for id in ids.iter().filter(|i| !known.contains(i)).take(30) {
                    if let Ok(u) = self.backend.user_info(id).await {
                        fetched.push(u);
                    }
                }
                if !fetched.is_empty() {
                    let _ = self.store.upsert_users(&fetched);
                    self.push_users().await;
                }
                let names = self.store.user_labels(&self.team).unwrap_or_default();
                // What the channel is, above who is in it. Both answer "should
                // I be reading this", and the topic is the half a member list
                // cannot tell you.
                let about = self
                    .store
                    .conversations(&self.team)
                    .unwrap_or_default()
                    .into_iter()
                    .find(|c| c.id == ch);
                let mut rows: Vec<ListRow> = Vec::new();
                if let Some(c) = &about {
                    for (what, value) in [
                        ("topic", c.topic.clone()),
                        ("purpose", c.purpose.clone()),
                        (
                            "members",
                            c.member_count.map(|n| n.to_string()).unwrap_or_default(),
                        ),
                    ] {
                        if !value.is_empty() {
                            rows.push(ListRow {
                                label: one_line(&value),
                                note: what.into(),
                                // Not a row to act on; picking it reopens the
                                // conversation, which is where it came from.
                                target: ListTarget::Info,
                            });
                        }
                    }
                }
                rows.extend(ids.into_iter().map(|id| {
                    ListRow {
                        label: names
                            .iter()
                            .find(|u| u.id == id)
                            .map(|u| u.label.clone())
                            .unwrap_or_else(|| id.as_str().to_string()),
                        note: String::new(),
                        target: ListTarget::User(id),
                    }
                }));
                self.emit(Event::List {
                    title: match &about {
                        Some(c) if !c.name.is_empty() => format!("#{}", c.name),
                        _ => "members".into(),
                    },
                    items: rows,
                })
                .await;
            }

            Command::ShowProfile(id) => {
                let mut found = self.store.user(&self.team, &id).ok().flatten();
                if found.is_none() {
                    if let Ok(u) = self.backend.user_info(&id).await {
                        let _ = self.store.upsert_users(std::slice::from_ref(&u));
                        found = self.store.user(&self.team, &id).ok().flatten();
                    }
                }
                match found {
                    Some(u) => self.emit(Event::Profile(Box::new(u))).await,
                    None => self.emit(Event::Notice("nobody by that id".into())).await,
                }
            }

            Command::Refresh => {
                self.boot().await;
            }
            Command::Shutdown => {}
        }
    }

    async fn open(&mut self, ch: ChannelId) {
        self.focused = Some(ch.clone());
        // Cached first: the pane fills before any request is made.
        if let Ok(cached) =
            self.store
                .latest_messages(&self.team, &ch, &self.self_id, self.page as usize)
        {
            if !cached.is_empty() {
                self.emit(Event::Messages {
                    channel: ch.clone(),
                    messages: cached,
                    append_older: false,
                })
                .await;
            }
        }

        let first = HistoryQuery {
            limit: self.page,
            ..Default::default()
        };
        match self.backend.history(&ch, first).await {
            Ok(page) => {
                self.store_page(&page.messages);
                self.emit(Event::Messages {
                    channel: ch,
                    messages: page.messages,
                    append_older: false,
                })
                .await;
            }
            Err(e) if e.kind == slk_api::ErrorKind::Auth => self.emit(Event::AuthLost).await,
            Err(e) => self.emit(Event::Notice(e.user_message())).await,
        }
    }

    async fn load_older(&mut self, ch: ChannelId, before: Ts) {
        match self
            .backend
            .history(
                &ch,
                HistoryQuery {
                    latest: Some(before),
                    limit: self.page,
                    ..Default::default()
                },
            )
            .await
        {
            Ok(page) => {
                self.store_page(&page.messages);
                self.emit(Event::Messages {
                    channel: ch,
                    messages: page.messages,
                    append_older: true,
                })
                .await;
            }
            Err(e) => self.emit(Event::Notice(e.user_message())).await,
        }
    }

    async fn open_thread(&mut self, ch: ChannelId, parent: Ts) {
        if let Ok(cached) = self.store.thread(&self.team, &ch, &self.self_id, &parent) {
            if !cached.is_empty() {
                self.emit(Event::Thread {
                    channel: ch.clone(),
                    parent: parent.clone(),
                    messages: cached,
                })
                .await;
            }
        }
        match self
            .backend
            .replies(&ch, &parent, HistoryQuery::default())
            .await
        {
            Ok(page) => {
                self.store_page(&page.messages);
                self.emit(Event::Thread {
                    channel: ch,
                    parent,
                    messages: page.messages,
                })
                .await;
            }
            Err(e) => self.emit(Event::Notice(e.user_message())).await,
        }
    }

    async fn send(
        &mut self,
        channel: ChannelId,
        thread: Option<Ts>,
        text: String,
        local_id: String,
        broadcast: bool,
    ) {
        // Optimistic: the row appears now, with a marker, and is replaced when
        // Slack answers. A chat client that waits for a round trip before
        // showing what you typed feels broken even when it is not.
        let pending_ts = Ts::new(format!("local:{local_id}"));
        let raw = serde_json::json!({
            "type": "message",
            "user": self.self_id.as_str(),
            "ts": pending_ts.as_str(),
            "text": text,
        });
        if let Some(mut m) = Message::parse(&self.team, &channel, &self.self_id, &raw) {
            m.thread_ts = thread.clone();
            m.delivery = Delivery::Pending(local_id.clone());
            self.emit(Event::Upserted {
                channel: channel.clone(),
                message: Box::new(m),
                replaces: None,
            })
            .await;
        }

        match self
            .backend
            .post(&channel, thread.as_ref(), &text, &local_id, broadcast)
            .await
        {
            Ok(ts) => {
                let raw = serde_json::json!({
                    "type": "message",
                    "user": self.self_id.as_str(),
                    "ts": ts.as_str(),
                    "text": text,
                });
                if let Some(mut m) = Message::parse(&self.team, &channel, &self.self_id, &raw) {
                    m.thread_ts = thread;
                    self.store_page(std::slice::from_ref(&m));
                    self.emit(Event::Upserted {
                        channel,
                        message: Box::new(m),
                        replaces: Some(pending_ts),
                    })
                    .await;
                }
            }
            Err(e) => {
                let raw = serde_json::json!({
                    "type": "message",
                    "user": self.self_id.as_str(),
                    "ts": pending_ts.as_str(),
                    "text": text,
                });
                if let Some(mut m) = Message::parse(&self.team, &channel, &self.self_id, &raw) {
                    m.delivery = Delivery::Failed(e.user_message());
                    self.emit(Event::Upserted {
                        channel,
                        message: Box::new(m),
                        replaces: Some(pending_ts),
                    })
                    .await;
                }
                self.emit(Event::Notice(format!("not sent: {}", e.user_message())))
                    .await;
            }
        }
    }

    /// Is this message worth interrupting someone for?
    ///
    /// A direct message always is. A mention of them always is. Anything else
    /// in a channel is not, which is the difference between a client people
    /// keep running and one they turn off by the second afternoon. A muted
    /// conversation is never worth it, whatever is in it.
    async fn consider_notifying(&mut self, channel: &ChannelId, m: &Message) {
        let Ok(convs) = self.store.conversations(&self.team) else {
            return;
        };
        let Some(conv) = convs.iter().find(|c| c.id == *channel) else {
            return;
        };
        if conv.is_muted {
            return;
        }
        // A keyword counts as a mention: that is what a highlight word is
        // for, and a notification that does not say why it happened is worse
        // than none.
        let mention = m.mentions(&self.self_id) || keyword_matches(&self.keywords, &m.body.plain());
        if !conv.is_dm() && !mention {
            return;
        }

        let who = match &m.author {
            slk_core::Author::User(u) => self
                .store
                .user_labels(&self.team)
                .unwrap_or_default()
                .into_iter()
                .find(|x| &x.id == u)
                .map(|x| x.label)
                .unwrap_or_else(|| u.as_str().to_string()),
            slk_core::Author::Bot { name, .. } => name.clone(),
            slk_core::Author::System => "Slack".into(),
        };
        let conversation = if conv.is_dm() {
            who.clone()
        } else {
            format!("#{}", conv.name)
        };

        self.emit(Event::Notify {
            channel: channel.clone(),
            conversation,
            who,
            text: m.body.plain(),
            mention,
        })
        .await;
    }

    /// Re-read one message from the server, after a write whose result we did
    /// not guess at or whose optimistic guess turned out wrong.
    async fn refresh_message(&mut self, ch: &ChannelId, ts: &Ts) {
        let q = HistoryQuery {
            latest: Some(ts.clone()),
            oldest: Some(ts.clone()),
            limit: 1,
            inclusive: true,
            ..Default::default()
        };
        if let Ok(page) = self.backend.history(ch, q).await {
            if let Some(m) = page.messages.into_iter().find(|m| m.ts == *ts) {
                self.store_page(std::slice::from_ref(&m));
                self.emit(Event::Upserted {
                    channel: ch.clone(),
                    message: Box::new(m),
                    replaces: Some(ts.clone()),
                })
                .await;
            }
        }
    }

    async fn mark_read(&mut self, ch: ChannelId, ts: Ts) {
        let _ = self.store.set_last_read(&self.team, &ch, &ts);
        self.push_sidebar().await;
        if let Err(e) = self.backend.mark(&ch, &ts).await {
            debug!("mark failed: {e}");
        }
    }

    async fn on_realtime(&mut self, ev: RtEvent) {
        match ev {
            RtEvent::Hello => self.emit(Event::Connected).await,

            RtEvent::Message { channel, ts, raw } => {
                let Some(m) = Message::parse(&self.team, &channel, &self.self_id, &raw) else {
                    return;
                };
                self.store_page(std::slice::from_ref(&m));
                // A message of our own echoing back is not unread, does not
                // make the sidebar blink, and certainly does not interrupt us.
                let from_self =
                    matches!(&m.author, slk_core::Author::User(u) if *u == self.self_id);
                if !from_self {
                    self.consider_notifying(&channel, &m).await;
                }
                self.emit(Event::Upserted {
                    channel: channel.clone(),
                    message: Box::new(m),
                    replaces: None,
                })
                .await;
                if !from_self {
                    let _ = ts;
                    self.push_sidebar().await;
                }
            }

            RtEvent::MessageChanged { channel, ts, raw } => {
                if let Some(m) = Message::parse(&self.team, &channel, &self.self_id, &raw) {
                    self.store_page(std::slice::from_ref(&m));
                    self.emit(Event::Upserted {
                        channel,
                        message: Box::new(m),
                        replaces: Some(ts),
                    })
                    .await;
                }
            }

            RtEvent::MessageDeleted { channel, ts } => {
                self.emit(Event::Deleted { channel, ts }).await;
            }

            RtEvent::ReactionChanged { channel, ts, .. } => {
                // The event says which reaction changed but not the resulting
                // counts, and guessing them is how two clients drift apart.
                self.refresh_message(&channel, &ts).await;
            }

            RtEvent::Marked { channel, ts } => {
                // A read on another device. It replaces our cursor; it never
                // increments or decrements one.
                let _ = self.store.set_last_read(&self.team, &channel, &ts);
                self.push_sidebar().await;
            }

            RtEvent::PresenceChanged { users, presence } => {
                let tag = format!("{presence:?}");
                let _ = self.store.set_presence(&self.team, &users, &tag);
                self.emit(Event::Presence { users, presence }).await;
            }

            RtEvent::Typing { channel, user } => {
                if user != self.self_id {
                    self.emit(Event::Typing { channel, user }).await;
                }
            }

            RtEvent::Disconnected(why) => {
                self.emit(Event::Disconnected(why)).await;
            }

            RtEvent::Unhandled(t) => debug!("unhandled realtime event: {t}"),

            _ => {}
        }
    }

    fn store_page(&mut self, msgs: &[Message]) {
        let rows: Vec<(Message, String)> =
            msgs.iter().map(|m| (m.clone(), m.raw.clone())).collect();
        if let Err(e) = self.store.upsert_messages(&rows) {
            warn!("storing messages: {e:#}");
        }
    }
}

/// One row of one of the lists.
#[derive(Debug, Clone)]
pub struct ListRow {
    pub label: String,
    pub note: String,
    pub target: ListTarget,
}

/// What picking a row does.
#[derive(Debug, Clone)]
pub enum ListTarget {
    /// Go to the message in its conversation.
    Message(ChannelId, Ts),
    /// Open the thread.
    Thread(ChannelId, Ts),
    /// Show the profile.
    User(UserId),
    /// Join a public channel, then open it.
    Join(ChannelId),
    /// A line that is there to be read, not chosen.
    Info,
}

/// Collapse newlines, because a list row is one line.
fn one_line(s: &str) -> String {
    s.split('\n')
        .map(str::trim)
        .filter(|p| !p.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}

/// A path that does not exist yet, by adding `-1`, `-2` and so on.
///
/// Two screenshots in a day are both called `image.png`, and silently
/// overwriting the first is the kind of thing a client only has to do once.
fn unique_path(want: &std::path::Path) -> std::path::PathBuf {
    if !want.exists() {
        return want.to_path_buf();
    }
    let stem = want
        .file_stem()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_default();
    let ext = want
        .extension()
        .map(|e| format!(".{}", e.to_string_lossy()))
        .unwrap_or_default();
    let dir = want.parent().unwrap_or(std::path::Path::new("."));
    for n in 1..1000 {
        let candidate = dir.join(format!("{stem}-{n}{ext}"));
        if !candidate.exists() {
            return candidate;
        }
    }
    want.to_path_buf()
}

/// `:emoji: some text for 2h` — the three parts of a status, split out.
///
/// Returns `(emoji, text, expires)`, where `expires` is a Unix time or zero
/// for "until I change it", which is what Slack's `status_expiration` means
/// by zero as well.
///
/// The `for …` suffix is only taken when it is the last thing on the line and
/// parses as a duration. "back in a bit, ask bob for the key" keeps every
/// word: guessing wrong here silently truncates somebody's status, and a
/// status is a thing other people read.
pub fn parse_status(text: &str, now: i64) -> (String, String, i64) {
    let text = text.trim();
    let (emoji, rest) = match text.strip_prefix(':') {
        Some(r) => match r.split_once(':') {
            Some((e, rest)) if !e.is_empty() && !e.contains(char::is_whitespace) => {
                (e.to_string(), rest.trim())
            }
            _ => (String::new(), text),
        },
        None => (String::new(), text),
    };

    let mut body = rest.to_string();
    let mut expires = 0;
    if let Some((head, tail)) = rest.rsplit_once(" for ") {
        let minutes = parse_duration(tail);
        if minutes > 0 {
            body = head.trim_end().to_string();
            expires = now + minutes as i64 * 60;
        }
    }
    (emoji, body, expires)
}

/// `30`, `30m`, `1h`, `2 hours` — minutes, or zero for "not a duration".
fn parse_duration(s: &str) -> u32 {
    let s = s.trim().to_lowercase();
    let (digits, unit): (String, String) = s.chars().partition(|c| c.is_ascii_digit());
    let Ok(n) = digits.parse::<u32>() else {
        return 0;
    };
    if n == 0 {
        return 0;
    }
    match unit.trim() {
        "" | "m" | "min" | "mins" | "minute" | "minutes" => n,
        "h" | "hr" | "hrs" | "hour" | "hours" => n * 60,
        "d" | "day" | "days" => n * 60 * 24,
        _ => 0,
    }
}

/// `30`, `30m`, `1h`, or nothing for "end it".
fn parse_minutes(s: &str) -> u32 {
    let s = s.trim().to_lowercase();
    if s.is_empty() || s == "off" || s == "end" {
        return 0;
    }
    let (digits, unit): (String, String) = s.chars().partition(|c| c.is_ascii_digit());
    let n: u32 = digits.parse().unwrap_or(30);
    match unit.trim() {
        "h" | "hr" | "hour" | "hours" => n * 60,
        _ => n,
    }
}

fn human_size(n: u64) -> String {
    const U: [&str; 4] = ["B", "KB", "MB", "GB"];
    let mut v = n as f64;
    let mut i = 0;
    while v >= 1024.0 && i < 3 {
        v /= 1024.0;
        i += 1;
    }
    if i == 0 {
        format!("{n} B")
    } else {
        format!("{v:.1} {}", U[i])
    }
}

/// What the sidebar draws. Re-exported so the binary need not depend on the
/// store crate directly.
pub use slk_store::StoredConversation as SidebarEntry;
